language: node_js
node_js:
  - "node"
  - "6"

cache: yarn

script:
  - yarn run typecheck
  - yarn run lint
  - yarn run test-once
  - yarn run build

before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - yarn global add codecov && codecov
